# Generated by Django 5.2 on 2025-05-03 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatsphere", "0002_analyticsusage_conversationfeedback_errorlog_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyticsusage",
            index=models.Index(
                fields=["bot", "timestamp"], name="chatsphere__bot_id_3d47cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsusage",
            index=models.Index(
                fields=["metric_type", "timestamp"],
                name="chatsphere__metric__670f43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bot",
            index=models.Index(fields=["user"], name="chatsphere__user_id_bbbae4_idx"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["document", "pinecone_vector_id"],
                name="chatsphere__documen_01820d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["bot", "user_id"], name="chatsphere__bot_id_ac9841_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationfeedback",
            index=models.Index(
                fields=["conversation"], name="chatsphere__convers_90901a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["bot", "status"], name="chatsphere__bot_id_dc696f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["timestamp", "service", "error_type"],
                name="chatsphere__timesta_4b58c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chatsphere__convers_fa0c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsourcestats",
            index=models.Index(
                fields=["document"], name="chatsphere__documen_7c694b_idx"
            ),
        ),
    ]
