# Generated by Django 5.2 on 2025-05-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatsphere", "0003_analyticsusage_chatsphere__bot_id_3d47cb_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legacymessage",
            name="room",
        ),
        migrations.RemoveField(
            model_name="legacymessage",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="LegacyMessage",
        ),
    ]
