version: '3.8'

services:
  db:
    image: postgres:13
    container_name: chatsphere-db-dev
    environment:
      - POSTGRES_DB=chatsphere
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: chatsphere-backend-dev
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-docker-dev-key
      - DJANGO_SETTINGS_MODULE=config.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend,frontend,*
      - CORS_ALLOWED_ORIGINS=http://localhost,http://127.0.0.1,http://localhost:5173,http://frontend:5173
      - DATABASE_URL=postgres://postgres:postgres@db:5432/chatsphere
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    image: node:18-alpine
    container_name: chatsphere-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  postgres_data_dev: